### ISSUE TITLE
IE11 with LazyControllers

### ISSUE THREAD

**Issue by nufaylr** [symfony/stimulus-bridge#40]
Hi, when we try to polyfill it always ignores template literals. I can see it generated via the following file under stimulus-bridge module ``@symfony/stimulus-bridge/src/webpack/create-controllers-module.js``

[create-controllers-module.js](https://github.com/symfony/stimulus-bridge/blob/main/src/webpack/create-controllers-module.js#L79)
```
if (fetchMode === 'lazy') {
                hasLazyControllers = true;
                moduleValueContents = `
new Promise((resolve, reject) => resolve({ default:
${generateLazyController(controllerMain, 6)}
  }))
                `.trim();
            }
```

Did anyone know how can polyfill lazy stimulus controller that will work with IE11?

Many thanks

**Comment by weaverryan** [comment]
Hi there!

Sorry for the slow reply :). The lazy functionality fundamentally relies on a `Promise`. So, you just need to "polyfill" this. Normally I think `Promise` is polyfilled automatically if you use it in your app. But since this is vendor code, that doesn't happen.

Try:

```js
import "core-js/modules/es.promise";
```

Adding a note to the docs, I think, would be helpful.

Cheers!

**Comment by nufaylr** [comment]
Hi @weaverryan Thank you for this. do we needs to add under bootstrap.js ?

**Comment by weaverryan** [comment]
Yes, that would do it :).

Btw, Stimulus 3 has dropped support for IE11 entirely. The next version of this library will use Stimulus 3 (but you can stay on the old version if you need IE 11 support).

Cheers!
