### ISSUE TITLE
LazyLoad controller feature isn't reliable: undefined method depending on the load speed of the controller. Solutions?

### ISSUE THREAD

**Issue by gremo** [symfony/stimulus-bridge#73]
1. I'm lazy-loading `test` controller using the comment `/* stimulusFetch: 'lazy' */`. The controller itself loads a third-party library (maybe a big one) and has the `start` method:

```typescript
// test_controller.ts
import { Controller } from '@hotwired/stimulus';

/* stimulusFetch: 'lazy' */
export default class extends Controller<HTMLElement> {
  start() { /* do things */ }
}
```

2. The `inview` controller will dispatch the event `inview:appear` when element enters the viewport (code omitted for brevity).

If you combine both, **a big issue occurs: the start method is `undefined` some times**, depending on `test` controller load speed:

```html
<div data-controller="test inview"
    data-action="inview:appear->test#start:once:stop">
</div>
```

When the element is on top of the page, the error has a great chance to occur. On the other hand, when controller is at bottom of the page, there is time to load the `test` controller and the error doesn't occur.

I'm pretty sure this occurs for the reason I'm explaining. What options do we have to solve the problem?

**Comment by weaverryan** [comment]
Sorry for missing this - I don't think we have any options to solve this problem - I think this type of controller is simply incompatible with being loaded lazily because your use-case requires the controller to be on the page as SOON as the markup appears.

I'm going to close - I don't think we can fix this - laziness just needs to be avoided for this situation.

Cheers!
